version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "development"
    labels:
      - "dependency-update"
    schedule:
      interval: "daily"

  - package-ecosystem: "pip"
    directory: "/"
    target-branch: "development"
    labels:
      - "dependency-update"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "*"
        update-types:
          ["version-update:semver-patch"]
