version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  labels:
    - "dependency-update"
  schedule:
    interval: weekly
    time: "06:00"
  open-pull-requests-limit: 10
- package-ecosystem: "github-actions"
  directory: "/"
  labels:
    - "dependency-update"
  schedule:
    interval: weekly
    time: "06:00"
  open-pull-requests-limit: 10
