name: Documentation issue
description: Report an issue with the documentation for the Home Assistant Windcentrale integration.
labels: [bug, documentation]
assignees:
  - jobvk
body:
  - type: markdown
    attributes:
      value: |
        # Documentation issue
        
        This issue form is for reporting documentation issue only!

        If you have a found a bug or error, please use the [bug report][bug].
        If you have a feature or enhancement request, please use the [discussions ideas page][dip].
        If you need help anything else please have a look on our [discussions page][dp].
        
        [bug]: https://github.com/jobvk/Home-Assistant-Windcentrale/issues/new?labels=bug&template=bug_report.yml
        [dip]: https://github.com/jobvk/Home-Assistant-Windcentrale/discussions/categories/ideas
        [dp]: https://github.com/jobvk/Home-Assistant-Windcentrale/discussions/

  - type: checkboxes
    attributes:
      label: Checklist
      options:
        - label: I checked if there is not a duplicate documentation issue issue with the same question.
          required: true
        - label:  This documentation issue is a bug related to the Windcentrale integration.
          required: true
        - label: This documentation issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
          required: true
        - label: I have filled out the documentation issue template to the best of my ability.
          required: true
  - type: markdown
    attributes:
      value: |
        # Problem
  - type: textarea
    id: the-problem
    validations:
      required: true
    attributes:
      label: The Problem
      description: >-
        Describe the documentation issue you are experiencing here to communicate to the maintainer.
        
        Provide a clear and concise description of what the problem is.
  - type: markdown
    attributes:
      value: |
        # Details
  - type: textarea
    id: additional-information
    attributes:
      label: Additional information
      description: >
        If you have any additional information for the maintainer, use the field below.
        Please note, you can attach screenshots or screen recordings here, by
        dragging and dropping files in the field below.